version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 12345
      APP_USER: miq
      APP_USER_PASSWORD: 12345
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

volumes:
  oracle-data:

networks:
  oracle-network:
